spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: school-service
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/api/schools/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**

# Eureka Client Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

# Enable Dynamic Route Discovery
spring.cloud.gateway.discovery.locator.enabled: true



#Actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      gateway:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8082